
let RenderingAnimals = [
    {id: 1,
    key: 1,
    animal: 'dog',
    category: 'mammal',
    emoji:  '🐶'},
    {id: 2,
    key: 2,
    animal: 'cat',
    category: 'mammal',
    emoji: '😻'},
    {id: 3,
    key: 3,
    animal: 'chicken',
    category: 'bird',
    emoji: '🐔'},
    {id: 4,
    key: 4,
    animal: 'cow',
    category: 'mammal',
    emoji: '🐄'},
    {id: 5,
    key: 5,
    animal: 'sheep',
    category: 'mammal',
    emoji: '🐑'},
    {id: 6,
    key: 6,
    animal: 'horse',
    category: 'mammal',
    emoji: '🐴'},
    {id: 7,
    key: 7,
    animal: 'whale',
    category: 'mammal',
    emoji: '🐳'}];


export default RenderingAnimals;